name: PS5 Firmware Monitor

on:
  schedule:
    # Runs automatically every 12 hours (00:00 UTC and 12:00 UTC)
    - cron: '0 0,12 * * *'
  workflow_dispatch: # Enables the manual "Run workflow" button

jobs:
  check-fw:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: python check_psn.py
